<?php

namespace Phpfreaks\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BaseEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends EntityRepository
{
}
