app:
    resource: @AppBundle/Controller/
    type:     annotation

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

ipb_login:
    path: /login/check-ipb
