article:
    pattern:  /articles
    defaults: { _controller: "PhpfreaksSiteBundle:Article:index" }

article_new:
    pattern:  /article/new
    defaults: { _controller: "PhpfreaksSiteBundle:Article:new" }

article_create:
    pattern:  /article/create
    defaults: { _controller: "PhpfreaksSiteBundle:Article:create" }
    requirements: { _method: post }

article_show:
    pattern:  /article/{slug}
    defaults: { _controller: "PhpfreaksSiteBundle:Article:show" }

article_edit:
    pattern:  /article/{slug}/edit
    defaults: { _controller: "PhpfreaksSiteBundle:Article:edit" }

article_update:
    pattern:  /article/{slug}/update
    defaults: { _controller: "PhpfreaksSiteBundle:Article:update" }
    requirements: { _method: post }

article_delete:
    pattern:  /article/{slug}/delete
    defaults: { _controller: "PhpfreaksSiteBundle:Article:delete" }
    requirements: { _method: post }
